language: python
git:
  depth: 200
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

dist: trusty
sudo: false
os: linux

cache:
  directories:
    - $HOME/local

addons:
  apt:
    packages:

env:
  global:
    - INSTALL_PREFIX=$HOME/local
    - BUILD_PREFIX=$HOME/src/builds
  matrix:
    - MPI=openmpi-1.6.5
    - MPI=openmpi-1.10.6
    - MPI=openmpi-2.0.2
    - MPI=openmpi-2.1.0

before_install:
  - mkdir -p $INSTALL_PREFIX
  - mkdir -p $BUILD_PREFIX
  - bash utils/travis_ci/travis_ci_install_mpi.sh $MPI $INSTALL_PREFIX $BUILD_PREFIX
  - export MPI_PREFIX=${INSTALL_PREFIX}/${MPI}
  - export PATH=${MPI_PREFIX}/bin:$PATH
  - export LIBRARY_PATH=${MPI_PREFIX}/lib:${MPI_PREFIX}/lib64:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=${MPI_PREFIX}/lib:${MPI_PREFIX}/lib64:$LD_LIBRARY_PATH
  - export CPATH=${MPI_PREFIX}/include:$CPATH
  - which ompi_info

install:
  - git config --global user.name mpi-array
  - git config --global user.email mpi-array@users.noreply.github.com
  - pip install flake8
  - pip install 'sphinx>=1.4,<1.6'
  - pip install travis-sphinx
  - pip install coveralls
  - python ./setup.py install

script:
  - ompi_info
  - utils/mpi4py_info.py
  - flake8 mpi_array
  - coverage run --source=mpi_array --omit='*logging*,*unittest*,*rtd*' -m mpi_array.tests;
  - # run tests on installed mpi_array
  - cd docs
  - python -m mpi_array.tests
  - cd ..
  - travis-sphinx build

after_success:
  - travis-sphinx --branches=dev deploy
  - coveralls
