language: python
git:
  depth: 200
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6-dev'

dist: trusty
sudo: false
os: linux

cache:
  pip: true
  apt: true
  directories:
    - $HOME/src/builds

addons:
  apt:
    packages:

env:
  global:
    - INSTALL_PREFIX=$HOME/local
    - BUILD_PREFIX=$HOME/src/builds
  matrix:
    - MPI=openmpi-1.10.5

before_install:
  - mkdir -p $INSTALL_PREFIX
  - mkdir -p $BUILD_PREFIX
  - bash utils/travis_ci/travis_ci_install_mpi.sh $MPI $INSTALL_PREFIX $BUILD_PREFIX
  - export PATH=${INSTALL_PREFIX}/bin:$PATH
  - export LIBRARY_PATH=${INSTALL_PREFIX}/lib:${INSTALL_PREFIX}/lib64:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:${INSTALL_PREFIX}/lib64:$LD_LIBRARY_PATH
  - export CPATH=${INSTALL_PREFIX}/include:$CPATH
  - ompi_info

install:
  - git config --global user.name mpi-array
  - git config --global user.email mpi-array@users.noreply.github.com
  - pip install flake8
  - pip install 'sphinx>=1.4'
  - pip install travis-sphinx
  - pip install coveralls
  - python ./setup.py install

script:
  - flake8 mpi_array
  - coverage run --source=mpi_array --omit='*logging*,*unittest*,*rtd*' -m mpi_array.tests;
  - # run tests on installed mpi_array
  - cd docs
  - python -m mpi_array.tests
  - cd ..
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3'* ]]; then travis-sphinx build; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3'* ]]; then travis-sphinx --branches=dev deploy; fi
  - coveralls
